Update dev.kodemy.deploy.yml

diff --git a/.github/workflows/dev.kodemy.deploy.yml b/.github/workflows/dev.kodemy.deploy.yml
--- a/.github/workflows/dev.kodemy.deploy.yml
+++ b/.github/workflows/dev.kodemy.deploy.yml
@@ -72,7 +72,9 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             echo "Validate npm"
-            which npm &> /dev/null || exit 1
+            echo "Current PATH: $PATH"
+            which npm || { echo "npm not found in PATH"; exit 1; }
+
   build-and-deploy:
     name: Build, Test, Deploy
     runs-on: self-hosted
